xxx-y                           := foo1.o
xxx-$(CONFIG_AAA_BBB) += foo2.o
 
ccflags-y += -D
ccflags-y += -I$(src)/nnn/
ccflags-y += -I$(src)//
ppp-y                           += /foo3.o
ppp-y                           += /foo4.o
